-- Richtung: r = nach rechts, l = nach links
signale = {
	-- Hauptsignale
    ["A"]    = {x = 9,  y = 10, richtung = "r",
        hp   = {pc = "signale", au = "right",  fb = 0},
        halt = {pc = "signale", au = "top", fb = 0},
    },
    ["AA"]   = {x = 9,  y = 8,  richtung = "r",
        hp   = {pc = "signale", au = "right",  fb = 1},
        halt = {pc = "signale", au = "top", fb = 1},
    },
    ["B"]    = {x = 16, y = 4,  richtung = "r",
        hp   = {pc = "signale", au = "right",  fb = 2},
        halt = {pc = "signale", au = "top", fb = 2},
    },
    ["F"]    = {x = 66, y = 8,  richtung = "l",
        hp   = {pc = "signale", au = "right",  fb = 3},
        halt = {pc = "signale", au = "top", fb = 3},
    },
    ["FF"]   = {x = 66, y = 10, richtung = "l",
        hp   = {pc = "signale", au = "right",  fb = 4},
        halt = {pc = "signale", au = "top", fb = 4},
    },
    ["G"]    = {x = 62, y = 2,  richtung = "l",
        hp   = {pc = "signale", au = "right",  fb = 5},
        halt = {pc = "signale", au = "top", fb = 5},
    },
    ["N1"]   = {x = 44, y = 12, richtung = "r",
        hp   = {pc = "signale", au = "right",  fb = 7},
        sh   = {pc = "signale", au = "left",  fb = 7},
        halt = {pc = "signale", au = "top", fb = 7},
    },
    ["N2"]   = {x = 44, y = 10, richtung = "r",
        hp   = {pc = "signale", au = "right",  fb = 8},
        sh   = {pc = "signale", au = "left",  fb = 8},
        halt = {pc = "signale", au = "top", fb = 8},
    },
    ["N4"]   = {x = 44, y = 6,  richtung = "r",
        hp   = {pc = "signale", au = "right",  fb = 9},
        sh   = {pc = "signale", au = "left",  fb = 9},
        halt = {pc = "signale", au = "top", fb = 9},
    },
    ["N5-6"] = {x = 55, y = 2,  richtung = "r",
        hp   = {pc = "signale", au = "right",  fb = 10},
        sh   = {pc = "signale", au = "left",  fb = 10},
        halt = {pc = "signale", au = "top", fb = 10},
    },
    ["P1"]   = {x = 31, y = 12, richtung = "l",
        hp   = {pc = "signale", au = "right",  fb = 11},
        sh   = {pc = "signale", au = "left",  fb = 11};
        halt = {pc = "signale", au = "top", fb = 11},
    },
    ["P3"]   = {x = 31, y = 8,  richtung = "l",
        hp   = {pc = "signale", au = "right",  fb = 12},
        sh   = {pc = "signale", au = "left",  fb = 12},
        halt = {pc = "signale", au = "top", fb = 12},
    },
    ["P4"]   = {x = 31, y = 6,  richtung = "l",
        hp   = {pc = "signale", au = "right",  fb = 13},
        sh   = {pc = "signale", au = "left",  fb = 13},
        halt = {pc = "signale", au = "top", fb = 13},
    },
    ["P5"]   = {x = 31, y = 4,  richtung = "l",
        hp   = {pc = "signale", au = "right",  fb = 14},
        sh   = {pc = "signale", au = "left",  fb = 14},
        halt = {pc = "signale", au = "top", fb = 14},
    },
    ["P6"]   = {x = 31, y = 2,  richtung = "l",
        hp   = {pc = "signale", au = "right",  fb = 15},
        sh   = {pc = "signale", au = "left",  fb = 15},
        halt = {pc = "signale", au = "top", fb = 15},
    },
	
	-- Sperrsignale
    ["L003X"] = {x = 45,  y = 08, richtung = "r",
        sh   = {pc = "signale", au = "left",  fb = 0},
        halt = {pc = "signale", au = "bottom", fb = 0},
    },
    ["L005X"] = {x = 45,  y = 04, richtung = "r",
        sh   = {pc = "signale", au = "left",  fb = 1},
        halt = {pc = "signale", au = "bottom", fb = 1},
    },
    ["L006X"] = {x = 45,  y = 02, richtung = "r",
        sh   = {pc = "signale", au = "left",  fb = 2},
        halt = {pc = "signale", au = "bottom", fb = 2},
    },
    ["L012X"] = {x = 16,  y = 10, richtung = "r",
        sh   = {pc = "signale", au = "left",  fb = 3},
        halt = {pc = "signale", au = "bottom", fb = 3},
    },
    ["L013X"] = {x = 16,  y = 08, richtung = "r",
        sh   = {pc = "signale", au = "left",  fb = 4},
        halt = {pc = "signale", au = "bottom", fb = 4},
    },
    ["L002Y"] = {x = 31,  y = 10, richtung = "l",
        sh   = {pc = "signale", au = "left",  fb = 5},
        halt = {pc = "signale", au = "bottom", fb = 5},
    },
    ["L022Y"] = {x = 60,  y = 10, richtung = "l",
        sh   = {pc = "signale", au = "left",  fb = 6},
        halt = {pc = "signale", au = "bottom", fb = 6},
    },
}

fsZiele = {
    ["BR"]  = {x = 09, y = 04, laenge = 6},
    ["SF"]  = {x = 01, y = 08, laenge = 7},
    ["SFG"] = {x = 01, y = 10, laenge = 7},
    ["EH"]  = {x = 65, y = 02, laenge = 6},
    ["TLG"] = {x = 69, y = 08, laenge = 7},
    ["TL"]  = {x = 69, y = 10, laenge = 7},
    ["012"] = {x = 12, y = 10, laenge = 3},
    ["013"] = {x = 12, y = 08, laenge = 3},
    ["022"] = {x = 62, y = 10, laenge = 3},
}

bahnuebergaenge = {}

gleise = {
    ["001"] = {x = 34, y = 12, pc = "belegung", au = "right", fb = 0, text = "--- 1 ---"},
    ["002"] = {x = 34, y = 10, pc = "belegung", au = "right", fb = 1, text = "--- 2 ---"},
    ["003"] = {x = 34, y = 08, pc = "belegung", au = "right", fb = 2, text = "--- 3 ---"},
    ["004"] = {x = 34, y = 06, pc = "belegung", au = "right", fb = 3, text = "--- 4 ---"},
    ["005"] = {x = 34, y = 04, pc = "belegung", au = "right", fb = 4, text = "--- 5 ---"},
    ["006"] = {x = 34, y = 02, pc = "belegung", au = "right", fb = 5, text = "--- 6 ---"},
    ["BR"]  = {x = 12, y = 04, pc = "belegung", au = "right", fb = 6, text = "<<-"},
    ["SF"]  = {x = 05, y = 08, pc = "belegung", au = "right", fb = 7, text = "<<-"},
    ["SFG"] = {x = 05, y = 10, pc = "belegung", au = "right", fb = 8, text = "<<-"},
    ["EH"]  = {x = 65, y = 02, pc = "belegung", au = "right", fb = 9, text = "->>"},
    ["TLG"] = {x = 69, y = 08, pc = "belegung", au = "right", fb = 10, text = "->>"},
    ["TL"]  = {x = 69, y = 10, pc = "belegung", au = "right", fb = 11, text = "->>"},
    ["012"] = {x = 12, y = 10, pc = "belegung", au = "right", fb = 12, text = "-<-"},
    ["013"] = {x = 12, y = 08, pc = "belegung", au = "right", fb = 13, text = "-<-"},
    ["022"] = {x = 62, y = 10, pc = "belegung", au = "right", fb = 14, text = "->-"},
}
weichen = {
	["W1/2"]   = {pc = "weiche", au = "right", fb = 0},
	["W3/4"]   = {pc = "weiche", au = "right", fb = 1},
	["W5/6"]   = {pc = "weiche", au = "right", fb = 2},
	["W11/12"] = {pc = "weiche", au = "right", fb = 4},
	["W13/14"] = {pc = "weiche", au = "right", fb = 5},
	["W15/16"] = {pc = "weiche", au = "right", fb = 6},
	["W21"]    = {pc = "weiche", au = "right", fb = 8},
	["W22"]    = {pc = "weiche", au = "right", fb = 9},
	["W23"]    = {pc = "weiche", au = "right", fb = 12},
	["W24"]    = {pc = "weiche", au = "right", fb = 13},
}
fahrstrassenteile = {
	["W22L/2"] = {x = 28, y = 02, text = "--"},
	["W23R"]   = {x = 47, y = 02, text = "----"},
	["W23"]    = {x = 52, y = 02, text = "--"},
	["026"]    = {x = 58, y = 02, text = "---"},
	
	["W22L/1"] = {x = 26, y = 03, text = "/"},
	["W23L/2"] = {x = 50, y = 03, text = "/"},
	
	["W21"]    = {x = 19, y = 04, text = "---"},
	["W21L"]   = {x = 23, y = 04, text = "--"},
	["W22R"]   = {x = 26, y = 04, text = "----"},
	["W23L/1"] = {x = 47, y = 04, text = "--"},
	
	["W21R/1"] = {x = 23, y = 05, text = "\\"},
	
	["W21R/2"] = {x = 25, y = 06, text = "--"},
	["W4"]     = {x = 28, y = 06, text = "--"},
	["W11R/1"] = {x = 47, y = 06, text = "--"},
	
	["W4L"]    = {x = 26, y = 07, text = "/"},
	["W11R/2"] = {x = 50, y = 07, text = "\\"},
	
	["W2R"]    = {x = 18, y = 08, text = "----"},
	["W2"]     = {x = 23, y = 08, text = "--"},
	["W3R"]    = {x = 26, y = 08, text = "----"},
	["W12L"]   = {x = 47, y = 08, text = "----"},
	["W12"]    = {x = 52, y = 08, text = "--"},
	["W15L"]   = {x = 55, y = 08, text = "----------"},
	
	["W1L"]    = {x = 21, y = 09, text = "/"},
	["W15R"]   = {x = 55, y = 09, text = "\\"},
	
	["W1"]     = {x = 18, y = 10, text = "--"},
	["W1R"]    = {x = 21, y = 10, text = "----"},
	["W5L"]    = {x = 26, y = 10, text = "----"},
	["W14R"]   = {x = 47, y = 10, text = "----"},
	["W16L"]   = {x = 52, y = 10, text = "----"},
	["W16"]    = {x = 57, y = 10, text = "--"},
	
	["W6R/1"]  = {x = 26, y = 11, text = "\\"},
	["W13L/2"] = {x = 50, y = 11, text = "/"},
	
	["W6R/2"]  = {x = 28, y = 12, text = "--"},
	["W13L/1"] = {x = 47, y = 12, text = "--"},
}
fahrstrassen = {
    ["A.N1"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 0},
        steller = {pc = "fsOst", au = "top",  fb = 0},
        aufloeser = {pc = "fsOst", au = "right",  fb = 0},
        fsTeile = {"W1","W1R","W6R"},
		weichen = {"W5/6"},
    },
    ["A.N2"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 1},
        steller = {pc = "fsOst", au = "top",  fb = 1},
        aufloeser = {pc = "fsOst", au = "right",  fb = 1},
        fsTeile = {"W1","W1R","W5L"},
		weichen = {},
    },
    ["A.N4"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 2},
        steller = {pc = "fsOst", au = "top",  fb = 2},
        aufloeser = {pc = "fsOst", au = "right", fb = 2},
        fsTeile = {"W1","W1L","W2","W4L","W4"},
		weichen = {"W1/2","W3/4"},
    },
    ["AA.N4"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 3},
        steller = {pc = "fsOst", au = "top",  fb = 3},
        aufloeser = {pc = "fsOst", au = "right", fb = 3},
        fsTeile = {"W2R","W2","W4L","W4"},
		weichen = {"W3/4"},
    },
    ["B.N4"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 4},
        steller = {pc = "fsOst", au = "top",  fb = 4},
        aufloeser = {pc = "fsOst", au = "right", fb = 4},
        fsTeile = {"W21","W21R","W4"},
		weichen = {"W21"},
    },
    ["B.L005X"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 5},
        steller = {pc = "fsOst", au = "top",  fb = 5},
        aufloeser = {pc = "fsOst", au = "right", fb = 5},
        fsTeile = {"W21","W21L","W22R"},
		weichen = {},
    },
    ["B.L006X"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 6},
        steller = {pc = "fsOst", au = "top",  fb = 6},
        aufloeser = {pc = "fsOst", au = "right", fb = 6},
        fsTeile = {"W21","W21L","W22L"},
		weichen = {"W22"},
    },
	
    ["F.P3"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 7},
        steller = {pc = "fsOst", au = "top",  fb = 7},
        aufloeser = {pc = "fsOst", au = "right", fb = 7},
        fsTeile = {"W15L","W12","W12L"},
		weichen = {},
    },
    ["F.P4"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 8},
        steller = {pc = "fsOst", au = "top",  fb = 8},
        aufloeser = {pc = "fsOst", au = "right", fb = 8},
        fsTeile = {"W15L","W12","W11R"},
		weichen = {"W11/12"},
    },
    ["FF.P1"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 9},
        steller = {pc = "fsOst", au = "top",  fb = 9},
        aufloeser = {pc = "fsOst", au = "right", fb = 9},
        fsTeile = {"W16","W16L","W13L"},
		weichen = {"W13/14"},
    },
    ["FF.P3"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 10},
        steller = {pc = "fsOst", au = "top",  fb = 10},
        aufloeser = {pc = "fsOst", au = "right", fb = 10},
        fsTeile = {"W16","W15R","W12","W12L"},
		weichen = {"W15/16"},
    },
    ["FF.P4"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 11},
        steller = {pc = "fsOst", au = "top",  fb = 11},
        aufloeser = {pc = "fsOst", au = "right", fb = 11},
        fsTeile = {"W16","W15R","W12","W11R"},
		weichen = {"W15/16","W11/12"},
    },
    ["G.P5"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 12},
        steller = {pc = "fsOst", au = "top",  fb = 12},
        aufloeser = {pc = "fsOst", au = "right", fb = 12},
        fsTeile = {"026","W23","W23L"},
		weichen = {"W23"},
    },
    ["G.P6"] = {
		rangieren = false,
        melder = {pc = "fsOst", au = "left",  fb = 13},
        steller = {pc = "fsOst", au = "top",  fb = 13},
        aufloeser = {pc = "fsOst", au = "right", fb = 13},
        fsTeile = {"026","W23","W23R"},
		weichen = {},
	},
	
    ["N1.TL"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 0},
        steller = {pc = "fsWest", au = "top",  fb = 0},
        aufloeser = {pc = "fsWest", au = "right", fb = 0},
        fsTeile = {"W16","W16L","W13L"},
		weichen = {"W13/14"},
	},
    ["N2.TL"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 1},
        steller = {pc = "fsWest", au = "top",  fb = 1},
        aufloeser = {pc = "fsWest", au = "right", fb = 1},
        fsTeile = {"W16","W16L","W14R"},
		weichen = {},
	},
    ["N4.TL"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 2},
        steller = {pc = "fsWest", au = "top",  fb = 2},
        aufloeser = {pc = "fsWest", au = "right", fb = 2},
        fsTeile = {"W16","W15R","W12","W11R"},
		weichen = {"W11/12","W15/16"},
	},
    ["N4.TLG"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 3},
        steller = {pc = "fsWest", au = "top",  fb = 3},
        aufloeser = {pc = "fsWest", au = "right", fb = 3},
        fsTeile = {"W15L","W12","W11R"},
		weichen = {"W11/12"},
	},
    ["L005X.EH"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 4},
        steller = {pc = "fsWest", au = "top",  fb = 4},
        aufloeser = {pc = "fsWest", au = "right", fb = 4},
        fsTeile = {"026","W23","W23L"},
		weichen = {"W23"},
		signale = {"N5-6"},
	},
    ["L006X.EH"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 5},
        steller = {pc = "fsWest", au = "top",  fb = 5},
        aufloeser = {pc = "fsWest", au = "right", fb = 5},
        fsTeile = {"026","W23","W23R"},
		weichen = {},
		signale = {"N5-6"},
	},
	
    ["P1.SFG"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 6},
        steller = {pc = "fsWest", au = "top",  fb = 6},
        aufloeser = {pc = "fsWest", au = "right", fb = 6},
        fsTeile = {"W1","W1R","W6R"},
		weichen = {"W5/6"},
	},
    ["P3.SFG"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 7},
        steller = {pc = "fsWest", au = "top",  fb = 7},
        aufloeser = {pc = "fsWest", au = "right", fb = 7},
        fsTeile = {"W1","W1L","W2","W3R"},
		weichen = {"W1/2"},
	},
    ["P4.SFG"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 8},
        steller = {pc = "fsWest", au = "top",  fb = 8},
        aufloeser = {pc = "fsWest", au = "right", fb = 8},
        fsTeile = {"W1","W1L","W2","W4L","W4"},
		weichen = {"W1/2","W3/4"},
	},
    ["P3.SF"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 9},
        steller = {pc = "fsWest", au = "top",  fb = 9},
        aufloeser = {pc = "fsWest", au = "right", fb = 9},
        fsTeile = {"W2R","W2","W3R"},
		weichen = {},
	},
    ["P4.SF"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 10},
        steller = {pc = "fsWest", au = "top",  fb = 10},
        aufloeser = {pc = "fsWest", au = "right", fb = 10},
        fsTeile = {"W2R","W2","W4L","W4"},
		weichen = {"W3/4"},
	},
    ["P4.BR"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 11},
        steller = {pc = "fsWest", au = "top",  fb = 11},
        aufloeser = {pc = "fsWest", au = "right", fb = 11},
        fsTeile = {"W21","W21R","W4"},
		weichen = {"W21"},
	},
    ["P5.BR"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 12},
        steller = {pc = "fsWest", au = "top",  fb = 12},
        aufloeser = {pc = "fsWest", au = "right", fb = 12},
        fsTeile = {"W21","W21L","W22R"},
		weichen = {},
	},
    ["P6.BR"] = {
		rangieren = false,
        melder = {pc = "fsWest", au = "left",  fb = 13},
        steller = {pc = "fsWest", au = "top",  fb = 13},
        aufloeser = {pc = "fsWest", au = "right", fb = 13},
        fsTeile = {"W21","W21L","W22L"},
		weichen = {"W22"},
    },
	
	-- Rangierstrassen
    ["L012X-N1"] = {
		rangieren = true,
        melder = {pc = "rfOst", au = "left",  fb = 0},
        steller = {pc = "rfOst", au = "top",  fb = 0},
        aufloeser = {pc = "rfOst", au = "right",  fb = 0},
        fsTeile = {"W1","W1R","W6R"},
		weichen = {"W5/6"},
    },
    ["L012X-N2"] = {
		rangieren = true,
        melder = {pc = "rfOst", au = "left",  fb = 1},
        steller = {pc = "rfOst", au = "top",  fb = 1},
        aufloeser = {pc = "rfOst", au = "right",  fb = 1},
        fsTeile = {"W1","W1R","W5L"},
		weichen = {},
    },
    ["L012X-L003X"] = {
		rangieren = true,
        melder = {pc = "rfOst", au = "left",  fb = 2},
        steller = {pc = "rfOst", au = "top",  fb = 2},
        aufloeser = {pc = "rfOst", au = "right", fb = 2},
        fsTeile = {"W1","W1L","W2","W3R"},
		weichen = {"W1/2"},
    },
    ["L012X-N4"] = {
		rangieren = true,
        melder = {pc = "rfOst", au = "left",  fb = 3},
        steller = {pc = "rfOst", au = "top",  fb = 3},
        aufloeser = {pc = "rfOst", au = "right", fb = 3},
        fsTeile = {"W1","W1L","W2","W4L","W4"},
		weichen = {"W1/2","W3/4"},
    },
    ["L013X-L003X"] = {
		rangieren = true,
        melder = {pc = "rfOst", au = "left",  fb = 4},
        steller = {pc = "rfOst", au = "top",  fb = 4},
        aufloeser = {pc = "rfOst", au = "right", fb = 4},
        fsTeile = {"W2R","W2","W3R"},
		weichen = {},
    },
    ["L013X-N4"] = {
		rangieren = true,
        melder = {pc = "rfOst", au = "left",  fb = 5},
        steller = {pc = "rfOst", au = "top",  fb = 5},
        aufloeser = {pc = "rfOst", au = "right", fb = 5},
        fsTeile = {"W2R","W2","W4L","W4"},
		weichen = {"W3/4"},
    },
	
	["L022Y-P1"] = {
		rangieren = true,
        melder = {pc = "rfOst", au = "left",  fb = 6},
        steller = {pc = "rfOst", au = "top",  fb = 6},
        aufloeser = {pc = "rfOst", au = "right", fb = 6},
        fsTeile = {"W16","W16L","W13L"},
		weichen = {"W13/14"},
    },
	["L022Y-L002Y"] = {
		rangieren = true,
        melder = {pc = "rfOst", au = "left",  fb = 7},
        steller = {pc = "rfOst", au = "top",  fb = 7},
        aufloeser = {pc = "rfOst", au = "right", fb = 7},
        fsTeile = {"W16","W16L","W14R"},
		weichen = {},
    },
    ["L022Y-P3"] = {
		rangieren = true,
        melder = {pc = "rfOst", au = "left",  fb = 8},
        steller = {pc = "rfOst", au = "top",  fb = 8},
        aufloeser = {pc = "rfOst", au = "right", fb = 8},
        fsTeile = {"W16","W15R","W12","W12L"},
		weichen = {"W15/16"},
    },
    ["L022Y-P4"] = {
		rangieren = true,
        melder = {pc = "rfOst", au = "left",  fb = 9},
        steller = {pc = "rfOst", au = "top",  fb = 9},
        aufloeser = {pc = "rfOst", au = "right", fb = 9},
        fsTeile = {"W16","W15R","W12","W11R"},
		weichen = {"W15/16","W11/12"},
    },
	
    ["N1-022"] = {
		rangieren = true,
        melder = {pc = "rfWest", au = "left",  fb = 0},
        steller = {pc = "rfWest", au = "top",  fb = 0},
        aufloeser = {pc = "rfWest", au = "right", fb = 0},
        fsTeile = {"W16","W16L","W13L"},
		weichen = {"W13/14"},
	},
    ["N2-022"] = {
		rangieren = true,
        melder = {pc = "rfWest", au = "left",  fb = 1},
        steller = {pc = "rfWest", au = "top",  fb = 1},
        aufloeser = {pc = "rfWest", au = "right", fb = 1},
        fsTeile = {"W16","W16L","W14R"},
		weichen = {},
	},
    ["L003X-022"] = {
		rangieren = true,
        melder = {pc = "rfWest", au = "left",  fb = 2},
        steller = {pc = "rfWest", au = "top",  fb = 2},
        aufloeser = {pc = "rfWest", au = "right", fb = 2},
        fsTeile = {"W16","W15R","W12","W12L"},
		weichen = {"W15/16"},
	},
    ["N4-022"] = {
		rangieren = true,
        melder = {pc = "rfWest", au = "left",  fb = 3},
        steller = {pc = "rfWest", au = "top",  fb = 3},
        aufloeser = {pc = "rfWest", au = "right", fb = 3},
        fsTeile = {"W16","W15R","W12","W11R"},
		weichen = {"W11/12","W15/16"},
	},
	
    ["P1-012"] = {
		rangieren = true,
        melder = {pc = "rfWest", au = "left",  fb = 4},
        steller = {pc = "rfWest", au = "top",  fb = 4},
        aufloeser = {pc = "rfWest", au = "right", fb = 4},
        fsTeile = {"W1","W1R","W6R"},
		weichen = {"W5/6"},
	},
    ["L002Y-012"] = {
		rangieren = true,
        melder = {pc = "rfWest", au = "left",  fb = 5},
        steller = {pc = "rfWest", au = "top",  fb = 5},
        aufloeser = {pc = "rfWest", au = "right", fb = 5},
        fsTeile = {"W1","W1R","W5L"},
		weichen = {},
	},
    ["P3-012"] = {
		rangieren = true,
        melder = {pc = "rfWest", au = "left",  fb = 6},
        steller = {pc = "rfWest", au = "top",  fb = 6},
        aufloeser = {pc = "rfWest", au = "right", fb = 6},
        fsTeile = {"W1","W1L","W2","W3R"},
		weichen = {"W1/2"},
	},
    ["P4-012"] = {
		rangieren = true,
        melder = {pc = "rfWest", au = "left",  fb = 7},
        steller = {pc = "rfWest", au = "top",  fb = 7},
        aufloeser = {pc = "rfWest", au = "right", fb = 7},
        fsTeile = {"W1","W1L","W2","W4L","W4"},
		weichen = {"W1/2","W3/4"},
	},
    ["P3-013"] = {
		rangieren = true,
        melder = {pc = "rfWest", au = "left",  fb = 8},
        steller = {pc = "rfWest", au = "top",  fb = 8},
        aufloeser = {pc = "rfWest", au = "right", fb = 8},
        fsTeile = {"W2R","W2","W3R"},
		weichen = {},
	},
    ["P4-013"] = {
		rangieren = true,
        melder = {pc = "rfWest", au = "left",  fb = 9},
        steller = {pc = "rfWest", au = "top",  fb = 9},
        aufloeser = {pc = "rfWest", au = "right", fb = 9},
        fsTeile = {"W2R","W2","W4L","W4"},
		weichen = {"W3/4"},
	},
}

gleisbildDatei = "gleisbild.txt"
stellwerkName = "Montabau"
bildschirm = "right"
modem = "top"